== Requirements Classes for Functions

[[rc-functions]]
=== Requirements Class "Function Expressions"
==== Overview

This requirements class adds support for function call expressions.

===== Function call expressions

[#img-uml-class-functions]
.Functions UML Class Diagram
[plantuml, target=diagram-classes, format=png]
....
abstract class Expression

FunctionCallExpression --|> Expression
FunctionCallExpression : function: Function
FunctionCallExpression : arguments: Expression[0..*]
FunctionCallExpression *-- Function
FunctionCallExpression *-- Expression

Function : name: string
Function : parameters: map < string, type >
Function : returnType: type
....

.FunctionCallExpression class
[width="90%",options="header"]
|===
| Name      | Type       | Definition                 | multiplicity
| function  | Function   | Function to be called      | 1
| arguments | Expression | Arguments to the function  | 0..*
|===

.Function class
[width="90%",options="header"]
|===
| Name         | Type                 | Definition                 | multiplicity
| name         | string               | Name                       | 1
| parameters   | map < string, type > | Parameters                 | 1
| returnType   | type                 | Return type                | 1
|===

===== Standard functions

A standard function is a Function with a pre-determined set of parameters, return value and behavior that may be registered with a URI.
Requirements class in this section defines standard functions.

.Standard functions URI mapping
[width="90%",options="header"]
|===
| Key   | Value      | Definition
| uri   | Function   | A URI allows to identify standard functiona, even if identical function names are used in different encoding, extension or implementations for different behaviors.
|===

==== Requirements

include::../requirements/rc-functions.adoc[]

[[rc-math]]
=== Requirements Class "Math Functions"
==== Overview

[#img-uml-class-math-functions]
.Math Functions UML Diagram
[plantuml, target=diagram-classes, format=png]
....
interface MathFunctions
MathFunctions --|> Function : standard functions
MathFunctions : abs(x : double) double
MathFunctions : acos(x : double) double
MathFunctions : asin(x : double) double
MathFunctions : atan(x : double) double
MathFunctions : atan2(y : double, x : double) double
MathFunctions : ceil(x : double) double
MathFunctions : cos(x : double) double
MathFunctions : cosh(x : double) double
MathFunctions : exp(x : double) double
MathFunctions : floor(x : double) double
MathFunctions : log(x : double) double
MathFunctions : log10(x : double) double
MathFunctions : max(x : double, y : double) double
MathFunctions : min(x : double, y : double) double
MathFunctions : pow(x : double, y : double) double
MathFunctions : random() double
MathFunctions : rint(x : double) double
MathFunctions : round(x : double) long
MathFunctions : sin(x : double) double
MathFunctions : sinh(x : double) double
MathFunctions : sqrt(x : double) double
MathFunctions : tan(x : double) double
MathFunctions : tanh(x : double) double
....

==== Requirements
include::../requirements/rc-math-functions.adoc[]

[[rc-arrayrelations]]
=== Requirements Class "Array Relation Functions"
==== Overview

[#img-uml-class-array-relation-functions]
.Array Relation Functions UML Diagram
[plantuml, target=diagram-classes, format=png]
....
interface ArrayRelationFunctions
ArrayRelationFunctions --|> Function : standard functions
ArrayRelationFunctions : a_containedBy(array a, array b) bool
ArrayRelationFunctions : a_contains(array a, array b) bool
ArrayRelationFunctions : a_equals(array a, array b) bool
ArrayRelationFunctions : a_overlaps(array a, array b) bool
ArrayRelationFunctions --> ArrayExpression
....

.Array relation functions
[width="90%",options="header"]
|===
| Name            | Parameters         | Return type  | Definition
| a_containedBy   | (array a, array b) | bool         |
| a_contains      | (array a, array b) | bool         |
| a_equals        | (array a, array b) | bool         |
| a_overlaps      | (array a, array b) | bool         |
|===

==== Requirements

include::../requirements/rc-array-relations.adoc[]

[[rc-textmanipulation]]
=== Requirements Class "Text Manipulation Functions"
==== Overview

[#img-uml-class-text-manipulation-functions]
.Text Manipulation Functions UML Diagram
[plantuml, target=diagram-classes, format=png]
....
interface TextManipulationFunctions
TextManipulationFunctions --|> Function : standard functions
TextManipulationFunctions : caseInsensitize(string s) string
TextManipulationFunctions : accentInsensitize(string s) string
TextManipulationFunctions : lowerCase(string s) string
TextManipulationFunctions : upperCase(string s) string
TextManipulationFunctions : concatenate(string a, string b) string
TextManipulationFunctions : substitute(string s, string a, string b) string
TextManipulationFunctions : format(string f, ...) string
....

.Text manipulation functions
[width="90%",options="header"]
|===
| Name               | Parameters                     | Return type  | Definition
| caseInsensitize    | (string s)                     | string       |
| accentInsensitize  | (string s)                     | string       |
| lowerCase          | (string s)                     | string       |
| upperCase          | (string s)                     | string       |
| concatenate        | (string a, string b)           | string       |
| substitute         | (string s, string a, string b) | string       |
| format             | (string f, ...)                | string       |
|===

==== Requirements

include::../requirements/rc-text-manipulation.adoc[]

[[rc-geometrymanipulation]]
=== Requirements Class "Geometry Manipulation Functions"
==== Overview

[#img-uml-class-geometry-manipulation-functions]
.Geometry Manipulation Functions UML Diagram
[plantuml, target=diagram-classes, format=png]
....
interface GeometryManipulationFunctions
GeometryManipulationFunctions --|> Function : standard functions
GeometryManipulationFunctions : s_intersection(Geometry a, Geometry b) Geometry
GeometryManipulationFunctions : s_union(Geometry a, Geometry b) Geometry
GeometryManipulationFunctions : s_difference(Geometry a, Geometry b) Geometry
GeometryManipulationFunctions : s_symDifference(Geometry a, Geometry b) Geometry
GeometryManipulationFunctions : s_buffer(Geometry a, double d) Geometry
GeometryManipulationFunctions : s_convexHull(Geometry a) Geometry
GeometryManipulationFunctions : s_envelope(Geometry a) BoundingBox
GeometryManipulationFunctions : s_centroid(Geometry a) Point
GeometryManipulationFunctions : s_offsetCurve(Geometry a, double d) Geometry
GeometryManipulationFunctions : s_voronoiLines(Geometry a) Geometry
GeometryManipulationFunctions : s_voronoiPolygons(Geometry a) Geometry
GeometryManipulationFunctions : s_delaunayTriangles(Geometry a) Geometry
GeometryManipulationFunctions --> Geometry
....

.Geometry manipulation functions
[width="90%",options="header"]
|===
| Name            | Parameters               | Return type  | Definition
| s_intersection  | (Geometry a, Geometry b) | Geometry     |
| s_union         | (Geometry a, Geometry b) | Geometry     |
| s_difference    | (Geometry a, Geometry b) | Geometry     |
| s_symDifference | (Geometry a, Geometry b) | Geometry     |
| s_convexHull    | (Geometry a)             | Geometry     |
| s_buffer        | (Geometry a, double d)   | Geometry     |
| s_envelope      | (Geometry a)             | BoundingBox  |
| s_centroid      | (Geometry a)             | Point        |
| s_offsetCurve   | (Geometry a, double d)   | Geometry     |
| s_voronoiLines  | (Geometry a)             | Geometry     |
| s_voronoiPolygons | (Geometry a)           | Geometry     |
| s_delaunayTriangles | (Geometry a)          | Geometry     |
|===

==== Requirements

include::../requirements/rc-geometry-manipulation.adoc[]

=== Requirements Class "Recoding Function"

==== Overview

[#img-uml-class-recoding-functions]
.Recoding Functions UML Diagram
[plantuml, target=diagram-classes, format=png]
....
interface RecodingFunctions
RecodingFunctions --|> Function : standard functions
RecodingFunctions : recode(string s, map < string, string > m) string
....

.Recoding functions
[width="90%",options="header"]
|===
| Name            | Parameters               | Return type  | Definition
| recode          | (string s, map < string, string > m) | string |
|===

==== Requirements

include::../requirements/rc-recoding.adoc[]

[[rc-aggregation]]
=== Requirements Class "Aggregation"

==== Overview

Aggregate(expression to aggregate, aggregation method, array of dimensions to aggregate upon).

The following aggregation methods are supported: min, max, average, sum, first, last, median, stdDev. 

Basic example use of aggregate function to compute the minimum NDVI over time dimension:

`Aggregate((B08-B04)/(B08+B04), 'min', ['time'])`

Example use in CartoSym-CSS of to compute a minimum EVI over time dimension:

```
.title 'EVI Sentinel-2 Style'
.abstract 'Applying a color map to an aggregated minimal Enhanced Vegetation Index (EVI)_ of sentinel-2 data'
{
   singleChannel: Aggregate(2.5 * (B08/10000 - B04/10000) / (1 + B08/10000 + 6 * B04/10000 + -7.5 * B02/10000), 'min', ['time']);
   colorMap:
   [
      { -2.0, black }, { -1.1, #BFBFBF }, { -0.2, #DBDBDB },
      { -0.1, #FFFFE0 }, {  0.0, #FFFACC }, { 0.025, #EDE8B5 },
      { 0.05, #DED99C }, { 0.075, #CCC782 }, { 0.1, #BFB86B },
      { 0.125, #B0C261 }, { 0.15, #A3CC59 }, { 0.175, #91BF52 },
      { 0.2, #80B347 }, { 0.25, #70A340 }, { 0.3, #619636 },
      { 0.35, #4F8A2E }, { 0.4, #407D24 }, { 0.45, #306E1C },
      { 0.5, #216112 }, { 0.55, #F540A }, { 0.6, #004500 }
   ];
}
```

Example use in CartoSym-CSS of to use average of RGB bands over time dimension:

```
.title 'Average Sentinel-2 imagery over time'
.abstract ''
{
   colorChannels.r: Aggregate(B04, 'average', ['time']);
   colorChannels.g: Aggregate(B03, 'average', ['time']);
   colorChannels.b: Aggregate(B02, 'average', ['time']);
}
```

Example use in CartoSym-CSS of to use latest RGB bands over time dimension:

```
.title 'Use the latest Sentinel-2 imagery'
.abstract ''
{
   colorChannels.r: Aggregate(B04, 'last', ['time']);
   colorChannels.g: Aggregate(B03, 'last', ['time']);
   colorChannels.b: Aggregate(B02, 'last', ['time']);
}
```

==== Requirements

include::../requirements/rc-aggregation.adoc[]
